### PR TITLE
Removing unnecessary sphinx templates

### PR DESCRIPTION
**Pull request by DanPuzzuoli**
### Summary

As suggested by @coruscating , this is following [Terra #9712](https://github.com/Qiskit/qiskit-terra/pull/9712/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3) by @jakelishman .

### Details and comments

Removes out of date template files.

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
yeah, you still need to tell sphinx about `_templates` because your autosummary template files are stored there

**Comment by DanPuzzuoli** [comment]
@jakelishman do you mind reviewing this.

**Comment by jakelishman** [comment]
i already looked - should be good 👍

**Comment by DanPuzzuoli** [comment]
> i already looked - should be good 👍

Ah ty - I missed it since the squash/merge button wasn't available. Just added you to the team whose reviews grant merge permission :).

**Pull request merged**
